### ISSUE TITLE
ngc-float-button.component events triggered when float-item is clicked

### ISSUE THREAD

**Issue by Marshal27** [GustavoCostaW/ngc-float-button#12]
Just wanted to bring this to your attention, when clicking the ngc-float-item-button it triggers the events: Subject on the ngc-float-button. 

I needed a scenario when the parent button is clicked, it will have an independent click event from the children. I had to add the same @clicked output event emitter that is on the float-item to the float-button to do so.

here were my manual changes to the compiled library for anyone needing this. 

1. ngc-float-button.component.js line #13 add **EventEmitter** to the @angular/core import
2. in the constructor (i put mine on line #25) add **this.clicked = new EventEmitter();**
3. in line #165 I added **'clicked': [{ type: Output },],**

- May be a good idea to make the float-button event independent from the float-item events if there is not already a way to do this.
- If there is a way, I couldn't figure it out and apologize for creating this.

all in all thank you for all your work on this library, I needed this functionality in my project and your library saved me a lot of time coding it myself.

**Comment by GustavoCostaW** [comment]
Hi @xxNoxiouSxx thank you for issue and feedback, well, I didn't understand what you exactly want, but you can listen to events in float-button and also in float-button-item.


```html
<ngc-float-button icon="add" (click)="reactEventFloatButton()">
    <ngc-float-item-button icon="person_add" content="click me" (click)="reactEventFloatButtonItem()">></ngc-float-item-button>
</ngc-float-button>
```

What do you really want, can you explain more details? thank you.

**Comment by GustavoCostaW** [comment]
Closed because the author does not explained more details.

**Comment by yavarnia** [comment]
hey buddy, when i have multiple float action item button inside ngc-float-button the click event does not work properly and it just fire the click event for the last ngc-float-item-button item, please help what is problem?


<div class="action-buttons">
                  <ngc-float-button icon="more_horiz" direction="right" color="#f86c6b">
                    <ngc-float-item-button (click)="referralFor('Revoke',item)"  icon="clear" content="1"></ngc-float-item-button>
                    <ngc-float-item-button (click)="referralFor('Assignment',item)" icon="assignment_ind" content="2"></ngc-float-item-button>
                    <ngc-float-item-button (click)="referralFor('Suspension',item)" icon="pause" content="3"></ngc-float-item-button>
                    <ngc-float-item-button (click)="referralFor('Info',item)" icon="reply_all" content="4"></ngc-float-item-button>
                    <ngc-float-item-button (click)="referralFor('Comments',item)" icon="comment" content="5"></ngc-float-item-button>
</ngc-float-button>

**Comment by yavarnia** [comment]
`<div class="action-buttons">
                  <ngc-float-button icon="more_horiz" direction="right" color="#f86c6b">
                    <ngc-float-item-button (click)="referralFor('Revoke',item)"  icon="clear" content="1"></ngc-float-item-button>
                    <ngc-float-item-button (click)="referralFor('Assignment',item)" icon="assignment_ind" content="2"></ngc-float-item-button>
                    <ngc-float-item-button (click)="referralFor('Suspension',item)" icon="pause" content="3"></ngc-float-item-button>
                    <ngc-float-item-button (click)="referralFor('Info',item)" icon="reply_all" content="4"></ngc-float-item-button>
                    <ngc-float-item-button (click)="referralFor('Comments',item)" icon="comment" content="5"></ngc-float-item-button>
</ngc-float-button>`

**Comment by m-yazdani** [comment]
@yavarnia i have exactly same problem and i didn't figure what's the problem
