### ISSUE TITLE
Positioning with @angular/flex-layout

### ISSUE THREAD

**Issue by oberoivarun** [GustavoCostaW/ngc-float-button#13]
I'm using flex-layout module and having problems positioning the foat-button.

What is the recommended way to position the element? I understand flexbox doesn't work so well with absolute positioned elements.

**Comment by GustavoCostaW** [comment]
@oberoivarun Hey, the `ngc-float-button` can be an absolute element, with this you can use the `top`, `left`, `right` and `bottom` properties

check this demo:

https://stackblitz.com/edit/ngc-float-button-jakyyc?file=app%2Fapp.component.html
