### ISSUE TITLE
bug(AOT): latest angular  isDisabled inside ngc-float-button

### ISSUE THREAD

**Issue by Stradivario** [GustavoCostaW/ngc-float-button#14]
Please define variable isDisabled also inside constructor because now AOT compilation will not pass missing property isDisabled...

https://github.com/GustavoCostaW/ngc-float-button/blob/master/components/ngc-float-item-button.component.ts#L72

**Comment by GustavoCostaW** [comment]
@Stradivario thank you, was fixed in 1.2.1, just update!
