### ISSUE TITLE
Add disabled state to the individual items

### ISSUE THREAD

**Issue by duck-nukem** [GustavoCostaW/ngc-float-button#9]
Hi!

Awesome work with this, thanks for putting it together in the first place!

I think it could be enhanced with adding an attribute to the `ngc-float-item-button`s, so it could be toggled from the Component.

This works with the current version:

**HTML**
```
      <ngc-float-item-button
        icon="delete"
        content="{{ 'ACTIONS.DELETE' | translate }}"
        [ngClass]="{'disabled-fab-button': !isAnyRowSelected()}"
        (click)="deleteSelected()">
      </ngc-float-item-button>
```

**CSS**
```
.disabled-fab-button {
  pointer-events: none;
}

.disabled-fab-button ::ng-deep .fab-item {
  background-color: lightgray;
}
```

**Comment by GustavoCostaW** [comment]
hey @kreatemore thx for the issue, I didn't understand, what's the new attribute that you talk about?

**Comment by duck-nukem** [comment]
Hey @GustavoCostaW sorry for disappearing, I've added a PR with the changes I had in mind. If you have time, please review it.

**Comment by GustavoCostaW** [comment]
@kreatemore hey, thank you for the PR, I added some comments there.
